# SwiftLint Configuration for Sashimi

included:
  - Sashimi
  - TopShelf

excluded:
  - .build
  - build
  - DerivedData

# Rules
disabled_rules:
  - trailing_comma
  - identifier_name
  - type_name
  - line_length
  - blanket_disable_command  # File-level disables are intentional for API models and large cohesive types

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Rule configurations
force_cast:
  severity: warning

force_try:
  severity: warning

cyclomatic_complexity:
  warning: 15
  error: 25

function_body_length:
  warning: 60
  error: 100

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

nesting:
  type_level: 3
  function_level: 3

# Discouraged optional boolean - exclude API models (Jellyfin API uses optional bools)
discouraged_optional_boolean:
  severity: warning

# Custom rules
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: '^\s*print\s*\('
    message: "Use proper logging instead of print statements"
    severity: warning
