name: Sashimi
options:
  bundleIdPrefix: com.sashimi
  deploymentTarget:
    tvOS: "17.0"
  xcodeVersion: "15.0"
  defaultConfig: Release

schemes:
  Sashimi:
    build:
      targets:
        Sashimi: all
        TopShelf: all
        SashimiTests: [test]
    run:
      config: Release
    test:
      targets:
        - SashimiTests

targets:
  Sashimi:
    type: application
    platform: tvOS
    sources:
      - path: Sashimi
        excludes:
          - "**/.DS_Store"
    info:
      path: Sashimi/Info.plist
      properties:
        CFBundleDisplayName: Sashimi
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - sashimi
            CFBundleURLName: com.sashimi.app
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sashimi.app
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: 5.9
        SDKROOT: appletvos
        SUPPORTED_PLATFORMS: "appletvos appletvsimulator"
        SUPPORTS_MACCATALYST: false
        DEVELOPMENT_TEAM: S6WU9SVVDW
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_SKIP_APP_STORE_DEPLOYMENT: NO
        ENABLE_ONLY_ACTIVE_RESOURCES: YES
        ENABLE_BITCODE: NO
        ENABLE_PREVIEWS: NO
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: "App Icon & Top Shelf Image"
        ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME: ""
    entitlements:
      path: Sashimi/Sashimi.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.sashimi.app
    dependencies:
      - target: TopShelf

  TopShelf:
    type: app-extension
    platform: tvOS
    sources:
      - path: TopShelf
        excludes:
          - "**/.DS_Store"
    info:
      path: TopShelf/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.tv-top-shelf
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ContentProvider
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sashimi.app.topshelf
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: 5.9
        SDKROOT: appletvos
        SUPPORTED_PLATFORMS: "appletvos appletvsimulator"
        DEVELOPMENT_TEAM: S6WU9SVVDW
        CODE_SIGN_STYLE: Automatic
        SKIP_INSTALL: YES
        TVOS_DEPLOYMENT_TARGET: "17.0"
    entitlements:
      path: TopShelf/TopShelf.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.sashimi.app
    dependencies: []

  SashimiTests:
    type: bundle.unit-test
    platform: tvOS
    sources:
      - path: SashimiTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sashimi.app.tests
        SWIFT_VERSION: 5.9
        SDKROOT: appletvos
        SUPPORTED_PLATFORMS: "appletvos appletvsimulator"
        DEVELOPMENT_TEAM: S6WU9SVVDW
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Sashimi.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Sashimi"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: Sashimi
