name: Sashimi
options:
  bundleIdPrefix: com.sashimi
  deploymentTarget:
    tvOS: "17.0"
    iOS: "17.0"
  xcodeVersion: "15.0"
  defaultConfig: Release

schemes:
  Sashimi:
    build:
      targets:
        Sashimi: all
        TopShelf: all
        SashimiTests: [test]
    run:
      config: Release
    test:
      targets:
        - SashimiTests

  SashimiMobile:
    build:
      targets:
        SashimiMobile: all
    run:
      config: Release

targets:
  Sashimi:
    type: application
    platform: tvOS
    sources:
      - path: Sashimi
        excludes:
          - "**/.DS_Store"
          - "CatIcon.imagestack"
          - "ChopsticksIcon.imagestack"
          - "CatIcon.png"
          - "CatIcon@2x.png"
          - "ChopsticksIcon.png"
          - "ChopsticksIcon@2x.png"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    info:
      path: Sashimi/Info.plist
      properties:
        CFBundleDisplayName: Sashimi
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - sashimi
            CFBundleURLName: com.mondominator.sashimi
        CFBundleIcons:
          CFBundleAlternateIcons:
            - CatIcon
            - ChopsticksIcon
            - WhitefishIcon
            - FoxIcon
            - PandaIcon
            - RacoonIcon
            - ShrimpIcon
            - TunaIcon
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mondominator.sashimi
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 2
        SWIFT_VERSION: 5.9
        SDKROOT: appletvos
        SUPPORTED_PLATFORMS: "appletvos appletvsimulator"
        SUPPORTS_MACCATALYST: false
        DEVELOPMENT_TEAM: S6WU9SVVDW
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_SKIP_APP_STORE_DEPLOYMENT: NO
        ENABLE_ONLY_ACTIVE_RESOURCES: YES
        ENABLE_BITCODE: NO
        ENABLE_PREVIEWS: NO
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: "App Icon & Top Shelf Image"
        ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES: "CatIcon ChopsticksIcon WhitefishIcon FoxIcon PandaIcon RacoonIcon ShrimpIcon TunaIcon"
        ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME: ""
    entitlements:
      path: Sashimi/Sashimi.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.mondominator.sashimi
    dependencies:
      - target: TopShelf

  SashimiMobile:
    type: application
    platform: iOS
    sources:
      - path: SashimiMobile
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    info:
      path: SashimiMobile/Info.plist
      properties:
        CFBundleDisplayName: Sashimi
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - sashimi
            CFBundleURLName: com.mondominator.sashimi.mobile
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
        UIRequiresFullScreen: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mondominator.sashimi.mobile
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: 5.9
        SDKROOT: iphoneos
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: false
        TARGETED_DEVICE_FAMILY: "2"
        DEVELOPMENT_TEAM: S6WU9SVVDW
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_SKIP_APP_STORE_DEPLOYMENT: NO
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: SashimiMobile/SashimiMobile.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.mondominator.sashimi
    dependencies:
      - package: Nuke
        products:
          - Nuke
          - NukeUI

  TopShelf:
    type: app-extension
    platform: tvOS
    sources:
      - path: TopShelf
        excludes:
          - "**/.DS_Store"
    info:
      path: TopShelf/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.tv-top-shelf
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ContentProvider
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mondominator.sashimi.topshelf
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 2
        SWIFT_VERSION: 5.9
        SDKROOT: appletvos
        SUPPORTED_PLATFORMS: "appletvos appletvsimulator"
        DEVELOPMENT_TEAM: S6WU9SVVDW
        CODE_SIGN_STYLE: Automatic
        SKIP_INSTALL: YES
        TVOS_DEPLOYMENT_TARGET: "17.0"
    entitlements:
      path: TopShelf/TopShelf.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.mondominator.sashimi
    dependencies: []

  SashimiTests:
    type: bundle.unit-test
    platform: tvOS
    sources:
      - path: SashimiTests
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mondominator.sashimi.tests
        SWIFT_VERSION: 5.9
        SDKROOT: appletvos
        SUPPORTED_PLATFORMS: "appletvos appletvsimulator"
        DEVELOPMENT_TEAM: S6WU9SVVDW
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Sashimi.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Sashimi"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: Sashimi

packages:
  Nuke:
    url: https://github.com/kean/Nuke.git
    from: "12.0.0"
